version: '3.9'

services:
  traefik:
    image: traefik:v2.5
    restart: always
    command: 
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "0.0.0.0:3306:3306"

  adminer:
    image: adminer
    restart: always
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.adminer.rule=Host(`adminer-192-168-33-10.nip.io`)"
    #   - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    #   - "traefik.http.routers.adminer.entrypoints=web"
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:18080:8080"

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - "mongo_data:/data/db"
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-express:
    image: mongo-express:0.54
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "0.0.0.0:18082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      #ME_CONFIG_BASICAUTH_USERNAME: ""
      #ME_CONFIG_BASICAUTH_PASSWORD: ""

  redis:
    image: redis
    restart: always
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis_data:/data

  rediscommander:
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "0.0.0.0:18081:8081"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      DEFAULT_VHOST: "exchange_server"
      DEFAULT_USER: "rabbit"
      DEFAULT_PASS: "rabbit"
    ports:
      - "0.0.0.0:15672:15672"
      - "0.0.0.0:5672:5672"

volumes:
  mysql_data:
  mongo_data:
  redis_data:

networks:
  infra:
