version: '3.9'

services:
  nsqlookupd:
    image: nsqio/nsq:v1.2.0
    command: /nsqlookupd
    restart: always
    ports:
      - "0.0.0.0:4160:4160"
      - "0.0.0.0:4161:4161"

  nsqd1:
    image: nsqio/nsq:v1.2.0
    command: /nsqd --data-path=/data --mem-queue-size=0 --lookupd-tcp-address=nsqlookupd:4160 
      -broadcast-address=192.168.33.10
      -tcp-address=0.0.0.0:4150
      -http-address=0.0.0.0:4151
    restart: always
    depends_on:
      - nsqlookupd
    volumes:
      - nsq_data:/data
    ports:
      - "0.0.0.0:4150:4150"
      - "0.0.0.0:4151:4151"

  nsqadmin:
    image: nsqio/nsq:v1.2.0
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    restart: always
    depends_on:
      - nsqlookupd
    ports:
      - "0.0.0.0:4171:4171"

volumes:
  nsq_data:
