apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscommander
spec:
  selector:
    matchLabels:
      app: rediscommander
  template:
    metadata:
      labels:
        app: rediscommander
    spec:
      containers:
      - name: rediscommander
        image: rediscommander/redis-commander:latest
        ports:
        - name: http
          containerPort: 8081
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8081
          initialDelaySecends: 10
          periodSeconds: 5
        env:
          - name: REDIS_HOSTS
            value: local:redis-redis-ha.default.svc.cluster.local:6379
---
apiVersion: v1
kind: Service
metadata:
  name: rediscommander-svc
spec:
  type: NodePort
  selector:
    app: rediscommander
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002