version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  prometheus:
    image: prom/prometheus
    restart: always
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - traefik
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.role!=manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus-192-168-33-11.nip.io`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
        - "traefik.http.routers.prometheus.entrypoints=web"

  grafana:
    image: grafana/grafana-enterprise
    restart: always
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.role!=manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana-192-168-33-11.nip.io`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.http.routers.grafana.entrypoints=web"
    networks:
      - traefik

  jaeger:
    image: jaegertracing/all-in-one:1.25
    restart: always
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    deploy:
      replicas: 1
      # endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`jaeger-192-168-33-11.nip.io`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=16686"
        - "traefik.http.routers.prometheus.entrypoints=web"
    networks:
      - traefik

configs:
  prometheus_config:
    external: true

networks:
  traefik:
    external: true

volumes:
  portainer_data: