version: '3.9'

services:

  mysql:
    image: mysql:8.1
    restart: always
    volumes:
      - ./data/mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "dev"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "123456"
    command: [
      # 关闭二进制日志，主从 数据恢复功能将不可用, 与"--disable-log-bin"参数二选一
      "--skip-log-bin", 
      # 设置utf8字符集
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      # InnoDB 恢复 0正常启动，不强制恢复 1-6启用
      "--innodb-force-recovery=0",
      # 慢日志 x 秒
      "--long-query-time=5",
      "--slow-query-log=ON",
      "--slow-query-log-file=/var/lib/mysql_log/mysql-slow.log",
    ]
    ports:
      - "0.0.0.0:30601:3306"
    networks:
      - infra

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "0.0.0.0:30901:3306"
    depends_on:
      - mysql
    networks:
      - infra

  mongo:
    image: mongo:7.0
    restart: always
    volumes:
      - ./data/mongo_data:/data/db
      - ./data/mongo_configdb:/data/configdb
    ports:
      - "0.0.0.0:30602:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    networks:
      - infra

  mongo-express:
    image: mongo-express:1.0
    restart: always
    ports:
      - "0.0.0.0:30902:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "123456"
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
    networks:
      - infra

  redis:
    image: redis:7.2
    restart: always
    command: 
      - --requirepass "123456"
    ports:
      - "0.0.0.0:30603:6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - infra

  rediscommander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "0.0.0.0:30903:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - infra

networks:
  infra:
