version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.25
    restart: always
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    deploy:
      replicas: 1
      # endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`jaeger-192-168-33-11.nip.io`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=16686"
        - "traefik.http.routers.prometheus.entrypoints=web"
    networks:
      - traefik

networks:
  traefik:
    external: true
