version: "3.9"

services:
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9009:9009"
      - "0.0.0.0:9004:9004"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 4096M
    #     reservations:
    #       memory: 4096M
    networks:
      - infra

networks:
  infra:
    external: true

volumes:
  clickhouse_data:

