version: '3.9'
 
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 4096M
    #     reservations:
    #       memory: 4096M
    networks:
      - infra

networks:
  infra:
    external: true

volumes:
  elasticsearch_data:

