version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      DEFAULT_VHOST: "exchange_server"
      DEFAULT_USER: "rabbit"
      DEFAULT_PASS: "rabbit"
    ports:
      - "0.0.0.0:15672:15672"
      - "0.0.0.0:5672:5672"
    networks:
      - infra

networks:
  infra:
    external: true
