version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - infra

  rediscommander:
    image: rediscommander/redis-commander:latest
    restart: always
    deploy:
      replicas: 3
      placement:
        constraints:
          - "node.role!=manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rediscommander.rule=Host(`rediscommander-192-168-33-11.nip.io`)"
        - "traefik.http.services.rediscommander.loadbalancer.server.port=8081"
        - "traefik.http.routers.rediscommander.entrypoints=web"
        - "traefik.docker.lbswarm=true"
          # admin joyoo.vip
        - "traefik.http.middlewares.rediscommander-auth.basicauth.users=admin:$$apr1$$4fcNlBLI$$Ryvin9FrYWV8v5KFwko5K1"
        - "traefik.http.routers.rediscommander.middlewares=rediscommander-auth"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - infra

networks:
  traefik:
    external: true

volumes:
  redis_data:
