---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport
spec:
  # 副本数
  replicas: 3 
  selector: 
    matchLabels:
      app: nginx-nodeport
  template:
    metadata:
      labels:
        app: nginx-nodeport
    spec:
      containers:
      - name: nginx-nodeport
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-svc
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 80
    targetPort: 80